### PR TITLE
Spendings

### PR DESCRIPTION
**Pull request by RibhavKhanna**
#4  @Zircoz @haspdecrypted, I have completed the given task. please make it hacktoberfest accepted.

### CODE REVIEW

**Comment by Zircoz** [comment]
The delivery time feature is not giving delivery time it is giving the time between placing order and then shipping it. Those numbers don't make sense. I never got any order in 5 hours.

That being said, I will do some excel shit to check if whatever we are doing here makes logical sense. So, wait for it. I will mark them accepted before end of October.

**Review by Zircoz — CHANGES_REQUESTED** [review]
The delivery time func is not giving delivery time it is giving the time between placing order and then shipping it + add them to a file under functions/ directory.

**Comment by RibhavKhanna** [comment]
@Zircoz please check now.

**Comment by Zircoz** [comment]
@RibhavKhanna I made changes to your PR that you might wanna see https://github.com/Zircoz/AmazonSummarizer/commit/0d463c01aee4913bab5349d0901057a7fdc0ee5c

3 very quick suggestions:
1. Use meaningful identifier names.
2. Suggest changes to requirements if they are loosely defined.
3. iloc uses index# to get the column, try to use the label/name since index isn't guaranteed anywhere by previous parser functions.

Thanks for your work! :}

**Pull request merged**
